refactor: overhaul the startup banner design
vexide/vexide pull request #117
Opened 2024-08-17 22:12 UTC by Tropix126

## Describe the changes this PR makes. Why should it be merged?
Overhauls the startup banner design to be a lot prettier (and more compact):

![image](https://github.com/user-attachments/assets/ba8daa4f-fa72-4ed0-a3a4-178139296b34)

The theme of the banner is seasonal and changes based on the compile date.

2024-08-22 22:11 UTC, max-niederman requested changes

2024-08-22 22:11 UTC, max-niederman commented on packages/vexide-startup/src/banner/mod.rs
> +        compile_date = compile_time::date_str!(),
Won't this be the compile time of `vexide-startup`, not the actual binary like most users would expect? I think it would be better to either
1. hacky: add a type parameter which is instantiated with a type from the user crate, delaying codegen for this function until monomorphization time.
2. less hacky: parameterize this function by the compile time, and call it from a macro invoked from the user crate. This has the additional advantage that the user could specify a particular date for reproducible builds without just disabling the banner.

2024-08-27 13:31 UTC, Tropix126 commented on packages/vexide-startup/src/banner/mod.rs
> +        compile_date = compile_time::date_str!(),
I'm tempted to just remove the compile time, since the loss of reproducible builds is a problem and it requires compiling `time`.

2024-08-28 03:44 UTC, doinkythederp requested changes

2024-08-28 03:44 UTC, doinkythederp commented on packages/vexide-startup/src/banner/mod.rs
> +    const VEXIDE_VERSION: &str = "0.3.0";
This should probably be `env!("CARGO_PKG_VERSION")`

2024-08-28 03:44 UTC, doinkythederp commented on packages/vexide-startup/src/banner/mod.rs
> +"{lp1}=%%%%%#-  {ls}-#%%%%-\x1B[0m{lp1}  :*%%%%%+.\x1B{cv}   {emoji} vexide {vexide_version}\x1B[0m
Might be good to add a newline before the banner to separate it from the serial data of previously run programs - this would be especially useful if the previous program doesn't end off with a newline.

2024-08-28 12:29 UTC, Tropix126 commented on packages/vexide-startup/src/banner/mod.rs
> +    const VEXIDE_VERSION: &str = "0.3.0";
That will return the vexide-startup version which has a separate semver cycle from vexide.

2024-09-05 14:40 UTC, Gavin-Niederman approved these changes
LGTM (Let's get themed messages)

2024-09-05 14:42 UTC, merged