add: add support for customizable banner themes in the `vexide::main` macro
vexide/vexide pull request #127
Opened 2024-09-06 04:51 UTC by Gavin-Niederman

## Describe the changes this PR makes. Why should it be merged?
Title :3
## Additional Context
- These changes update the crate's interface (e.g. functions/modules added or changed).
- I have tested these changes on a VEX V5 brain.

2024-09-08 03:30 UTC, doinkythederp requested changes
Wrong button

2024-09-08 03:34 UTC, Gavin-Niederman commented on packages/vexide-startup/src/banner/themes.rs
> +//! #[vexide::main(banner(enabled = true, theme = CUSTOM_THEME))]
I consider that, but most people will just be using (enabled = false) or (theme = theme) and doing that with an option seems less readable to me

2024-09-08 03:34 UTC, Gavin-Niederman commented on packages/vexide-startup/src/banner/themes.rs
> +//! This theme can then be passed to the [`vexide::main`](https://docs.rs/vexide/latest/vexide/attr.main.html).
Yeah I meant to say vexide::main macro

2024-09-08 03:36 UTC, doinkythederp commented
Also BTW this makes the docs out of date for the `vexide::main` macro

2024-09-10 05:42 UTC, doinkythederp requested changes

2024-09-10 05:42 UTC, doinkythederp commented on packages/vexide-macro/src/lib.rs
> +/// #[vexide::main(theme = THEME_SYNTHWAVE)]
Should this be `main(banner(theme = THEME_SYNTHWAVE))`? Also see line 145.

2024-09-26 00:44 UTC, Gavin-Niederman commented on packages/vexide-macro/src/lib.rs
> +/// #[vexide::main(theme = THEME_SYNTHWAVE)]
fixed

2024-09-26 01:48 UTC, doinkythederp commented on packages/vexide-startup/src/banner/mod.rs
> +//! The banner can be printed with a theme using the [`print`] function.
IMO this should mention that the banner is automatically printed when using the `vexide::main` macro

2024-09-26 02:51 UTC, Gavin-Niederman commented on packages/vexide-startup/src/banner/mod.rs
> +//! The banner can be printed with a theme using the [`print`] function.
done

2024-09-26 02:52 UTC, doinkythederp approved these changes

2024-09-26 02:58 UTC, merged