feat: add backtraces
vexide/vexide pull request #130
Opened 2024-09-08 06:34 UTC by doinkythederp

## Describe the changes this PR makes. Why should it be merged?

Adds backtraces which are exposed through a new `Backtrace` struct.

Backtraces are shown alongside panic messages and can be manually captured using `Backtrace::capture` or `Backtrace::try_capture`. `Backtrace::capture` silently fails if the current environment does not support backtraces, such as in WASM environments or if the user manually disables including unwind tables with `RUSTFLAGS="-Cforce-unwind-tables=off"`.

## Additional Context
- I have tested these changes on a VEX V5 brain.
- These changes update the crate's interface (e.g. functions/modules added or changed).

Backtrace capturing is backed by LLVM libunwind and the resulting frames are instruction addresses that can be symbolized with `llvm-symbolizer` or `addr2line`.

Adding the libunwind library adds about 12k to vexide, bringing the basic example up to 62k. The unwind tables themselves are low-impact:

| No libunwind, no unwind tables | No unwind tables | Backtrace-ready |
|--------------------------------|------------------|-----------------|
| 50k | 62k | 63k |

This change is compatible with the previous version of the armv7a-vex-v5 target file, but backtraces will fail to capture frames.

2024-09-09 17:22 UTC, Tropix126 requested changes

2024-09-09 17:37 UTC, Tropix126 commented
I also think that we should consider putting this into an optional feature.

2024-09-09 18:20 UTC, doinkythederp commented on armv7a-vex-v5.json
> -        "ld.lld": [
This was actually just a reformatting change and I haven't changed the functionality of the target file's post-link-args.

2024-09-10 16:17 UTC, doinkythederp commented on packages/vexide-core/src/backtrace.rs
> +            }
This is mostly ready but I need to do some hardware testing to see if this code affects backtrace quality.

2024-09-10 16:45 UTC, doinkythederp commented
`unw_resume` in vex-libunwind should probably have the C-unwind abi

2024-09-11 23:32 UTC, Gavin-Niederman commented on armv7a-vex-v5.json
> -        "ld.lld": [
> any changes to this file should be done upstream to cargo-v5

^^ this

2024-09-11 23:52 UTC, doinkythederp commented on armv7a-vex-v5.json
> -        "ld.lld": [
> > any changes to this file should be done upstream to cargo-v5
> 
> ^^ this

That’s out of scope in this PR - if it’s merged, that would be the next step. But I can’t change cargo-v5 files from this PR and there’s no reason to update the cargo-v5 target file unless this PR is merged.

2024-09-19 02:46 UTC, Tropix126 approved these changes
LGTM otherwise

2024-09-19 02:46 UTC, Tropix126 commented on packages/vexide-core/Cargo.toml
> +default = ["unwind"]
I think that this should be called `backtrace` or similar until (or if) we get proper unwinding figured out.

2024-09-19 02:46 UTC, Gavin-Niederman approved these changes
LGTM

2024-09-19 02:56 UTC, doinkythederp commented on packages/vexide-core/Cargo.toml
> +default = ["unwind"]
That makes sense - I named this after the dependency (libunwind), but it's better for users for it to be named it after what it does (backtraces)

2024-09-19 02:59 UTC, doinkythederp commented
BTW I ran a formatter on the Cargo.toml files

2024-09-19 03:03 UTC, merged