docs: make general improvements
vexide/vexide pull request #132
Opened 2024-09-19 03:31 UTC by doinkythederp

## Describe the changes this PR makes. Why should it be merged?

Resolves the current problems detailed in #95

## Additional Context
- These are *only* non-code changes (e.g. documentation, README.md).

2024-09-19 06:05 UTC, doinkythederp commented
Also going to update changelog in this PR

2024-09-26 04:56 UTC, Gavin-Niederman requested changes
mostly good

2024-09-26 04:56 UTC, Gavin-Niederman commented on packages/vexide-core/src/competition.rs
> +    ///   We rely on lifetime parametrically of the `mk_*` functions for this (see the HRTBs above).
grammar

2024-09-26 04:56 UTC, Gavin-Niederman commented on packages/vexide-core/src/competition.rs
> +    /// The Driver Control (i.e. opcontrol) competition mode.
Consider linking to the variant.

2024-09-26 04:56 UTC, Gavin-Niederman commented on packages/vexide-devices/src/controller.rs
> +    VEXNet,
I think that this is an incorrect usage of upper camel case. VEX is one word.

2024-09-26 04:56 UTC, Gavin-Niederman commented on packages/vexide-devices/src/peripherals.rs
> +//! Both kinds of peripherals (i.e [`Peripherals`] and [`DynamicPeripherals`]) guarantee that a given port is only used to create one device.
Personally I prefer the version without i.e.

2024-09-26 04:56 UTC, Gavin-Niederman commented on packages/vexide-devices/src/screen.rs
> +    /// Draw operations are immediately applied to the screen without the need to call [`Screen::render`].
The notes about needing to call Screen::render should be added back.

2024-09-26 04:56 UTC, Gavin-Niederman commented on packages/vexide-devices/src/smart/imu.rs
> +        const AUTO_CALIBRATED = 0b10000;
Mark this as a breaking change in the changelog.

2024-09-26 04:56 UTC, Gavin-Niederman commented on packages/vexide/examples/adi.rs
> +        // not hog all the CPU while looping.
?

2024-09-26 04:56 UTC, Gavin-Niederman commented on packages/vexide/examples/adi_expander.rs
> +    // The `AdiExpander` API is almost identical to that of Peripherals.
should add links

2024-09-26 05:00 UTC, doinkythederp commented on packages/vexide-devices/src/controller.rs
> +    VEXNet,
Yeah I can see that, how about `VexNet`?

2024-09-26 05:02 UTC, doinkythederp commented on packages/vexide-core/src/competition.rs
> +    ///   We rely on lifetime parametrically of the `mk_*` functions for this (see the HRTBs above).
Oh, I see that now - I assumed this was a misspelling of "parametrically" but it's actually the concept of parametricity

2024-09-26 05:05 UTC, Gavin-Niederman commented on packages/vexide-devices/src/controller.rs
> +    VEXNet,
VexNet seems good to me :+1:

2024-09-26 05:05 UTC, doinkythederp commented on packages/vexide-devices/src/screen.rs
> +    /// Draw operations are immediately applied to the screen without the need to call [`Screen::render`].
I think they're still there: "…that can be swapped onto the screen by calling [`Screen::render`]". Unless you're talking about something else?

2024-09-26 05:06 UTC, Gavin-Niederman commented on packages/vexide-core/src/competition.rs
> +    /// The Driver Control (i.e. opcontrol) competition mode.
Wait just realized this is the docs for the variant. Mb

2024-09-26 05:08 UTC, doinkythederp commented on packages/vexide/examples/adi.rs
> +        // not hog all the CPU while looping.
This change is such a bikeshed, LOL. My reasoning is that "of" is redundant.

2024-09-26 05:12 UTC, doinkythederp commented on packages/vexide/examples/adi_expander.rs
> +    // The `AdiExpander` API is almost identical to that of Peripherals.
Not a doc comment so links wouldn't actually do anything really

2024-09-26 05:16 UTC, Gavin-Niederman commented on packages/vexide-devices/src/screen.rs
> +    /// Draw operations are immediately applied to the screen without the need to call [`Screen::render`].
I just think that it should be stated very clearly that nothing will be displayed if you don't call Screen::render in double buffered mode.

2024-09-26 05:17 UTC, Gavin-Niederman commented on packages/vexide/examples/adi_expander.rs
> +    // The `AdiExpander` API is almost identical to that of Peripherals.
Oh real didnt catch that.

2024-09-26 05:18 UTC, Gavin-Niederman commented on packages/vexide/examples/adi.rs
> +        // not hog all the CPU while looping.
I don't have a strong opinion on which one is better so I'll just resolve this lmao.

2024-09-27 00:47 UTC, Gavin-Niederman commented
This closes #101

2024-09-28 08:26 UTC, max-niederman requested changes

2024-09-28 08:26 UTC, max-niederman commented on packages/vexide-devices/src/adi/accelerometer.rs
> +    /// Gets the current acceleration measurement for this axis in G.
This should be a little g, not big G. It would probably be best to just say something like "in multiple's of Earth's gravity" or "in Earth gravities" or "in g (~9.8 m/s/s)".

2024-09-28 08:26 UTC, max-niederman commented on packages/vexide-devices/src/screen.rs
> +    /// Center point (coordinates) of the circle
What would this be if not coordinates? Ditto for the other explicit mentions of coordinates.

2024-09-29 00:52 UTC, doinkythederp commented on packages/vexide-devices/src/adi/accelerometer.rs
> +    /// Gets the current acceleration measurement for this axis in G.
I’ve also heard this unit referred to as “gees” before.

2024-09-29 01:25 UTC, Gavin-Niederman commented on packages/vexide-devices/src/adi/accelerometer.rs
> +    /// Gets the current acceleration measurement for this axis in G.
Who tf is out here calling it a goose

2024-09-29 17:40 UTC, Tropix126 commented on packages/vexide-devices/src/adi/accelerometer.rs
> +    /// Gets the current acceleration measurement for this axis in G.
> I’ve also heard this unit referred to as “gees” before.

![speechmemified_pasteimage (1)](https://github.com/user-attachments/assets/0059d0bf-009f-40f4-9609-fe5f4e59b777)

2024-10-04 17:28 UTC, Tropix126 approved these changes
LGTM

2024-10-05 01:28 UTC, Gavin-Niederman approved these changes
LGTM

2024-10-05 01:28 UTC, merged