refactor: more lints
vexide/vexide pull request #155
Opened 2024-10-09 02:55 UTC by doinkythederp

## Describe the changes this PR makes. Why should it be merged?

Adds more lints and then resolves them:
- [x] Adds must_use to constructors and getters
- [x] Documents losses in precision and uses `u32::from` and equivalents to prevent accidental changes that will cause losses in precision
- [x] Adds semicolons to places that were missing semicolons where it makes sense to add them
- [ ] Documents the errors returned by functions that return `Result`s
- [x] Adds separators to RGB hexes to improve readability
- [x] `BannerTheme` is now `Copy`
- [x] A few other minor changes suggested by Clippy

## Additional Context

2024-10-14 05:08 UTC, doinkythederp commented
TODO: update changelog

2024-10-14 18:59 UTC, Tropix126 requested changes
This in general seems good, although there are some places we might want an additional message with `#[must_use]`

2024-10-14 18:59 UTC, Tropix126 commented on packages/vexide-core/src/float/mod.rs
> +    #[must_use]
Think we should probably have a message here. This is `libstd`'s:

`#[must_use = "method returns a new number and does not mutate the original value"]`

2024-10-22 22:26 UTC, Tropix126 approved these changes
LGTM

2024-10-22 22:26 UTC, merged