feat(experimental): VEX EXP Support
vexide/vexide pull request #181
Opened 2024-10-15 23:11 UTC by Tropix126

## Describe the changes this PR makes. Why should it be merged?
Testing experimental support for crosscompilation the VEX EXP platform. Since EXP appears to share the same jump addresses as V5, this is a pretty trivial port (switching platform targets and writing a new linkerscript).

Completely untested, although I do have access to EXP hardware to test on via the SCORE office.

2024-10-16 01:37 UTC, Gavin-Niederman requested changes

2024-10-16 01:37 UTC, Gavin-Niederman commented on Cargo.toml
> +vex-sdk = { git = "https://github.com/vexide/vex-sdk" }
fluh

2024-10-16 01:37 UTC, Gavin-Niederman commented on packages/vexide-startup/src/lib.rs
> +        const MAGIC: u32 = vex_sdk::EX_SIG_MAGIC;
these cfgs are backwards

2024-10-16 01:38 UTC, Tropix126 commented on Cargo.toml
> +vex-sdk = { git = "https://github.com/vexide/vex-sdk" }
buh its a draft

2024-10-16 02:15 UTC, Gavin-Niederman commented on Cargo.toml
> +vex-sdk = { git = "https://github.com/vexide/vex-sdk" }
:3

2025-02-01 21:07 UTC, Tropix126 commented
will revisit at a later time (probably after we have a dedicated V5 target in `rustc`)

2025-02-01 21:07 UTC, closed without merging