refactor: ADI modules
vexide/vexide pull request #210
Opened 2024-11-03 02:14 UTC by Tropix126

## Describe the changes this PR makes. Why should it be merged?
This PR refactors the modules relating to ADI in `vexide_devices`. This is mainly documentation improvements, but also:
- Adds a proper `level` getter to `AdiDigitalOut` that calls to VEXos rather than just statically storing the level and hoping its low on program start.
- Adds a `toggle` method to `AdiDigitalOut`.
- (in the future) Removes `AdiSolenoid`.
- Resolves some rustdoc issues and improves docs in other unrelated modules.

2024-11-03 02:37 UTC, Gavin-Niederman requested changes
changelog :3

2024-11-04 21:09 UTC, Gavin-Niederman requested changes

2024-11-04 21:09 UTC, Gavin-Niederman commented on packages/vexide-devices/src/adi/light_sensor.rs
> +//! That being said, the sensor generally has a usable range of up to 6 feet, meaning it
Not really a reason not to merge, but has this been verified?

2024-11-06 03:16 UTC, Tropix126 commented on packages/vexide-devices/src/adi/light_sensor.rs
> +//! That being said, the sensor generally has a usable range of up to 6 feet, meaning it
This comment is based on vex's own technical documentation.

> 	Usable range of 0 to 6 feet

2024-11-06 03:39 UTC, Gavin-Niederman approved these changes
LGTM

2024-11-06 22:02 UTC, merged