fix(core): add `Send` + `Sync` impls for `RwLock`
vexide/vexide pull request #239
Opened 2024-11-19 22:47 UTC by zabackary

## Describe the changes this PR makes. Why should it be merged?

`Send` and `Sync` implementations were not created for `RwLock`, making the lock essentially useless in Rust's type system.

This PR also updates the generic `T` in `RwLock` to be `?Sized` for more flexibility.

## Additional Context
- I haven't tested these changes
- semver: minor

2024-11-19 22:47 UTC, zabackary reviewed
I suppose this should technically be `feat(core`, but it probably doesn't matter too much.

2024-11-20 05:58 UTC, Gavin-Niederman requested changes

2024-11-20 05:58 UTC, Gavin-Niederman commented on packages/vexide-core/src/sync/rwlock.rs
> +unsafe impl<T: ?Sized + Sync> Sync for RwLock<T> {}
This should be T: ?Sized + Send

2024-11-20 06:30 UTC, doinkythederp commented on packages/vexide-core/src/sync/rwlock.rs
> +unsafe impl<T: ?Sized + Sync> Sync for RwLock<T> {}
Can you make sure that’s consistent with the std RwLock? I’m pretty sure std::sync::RwLock needs T to be Sync to be Sync itself.

2024-11-20 07:04 UTC, zabackary commented on packages/vexide-core/src/sync/rwlock.rs
> +unsafe impl<T: ?Sized + Sync> Sync for RwLock<T> {}
https://doc.rust-lang.org/std/sync/struct.RwLock.html#impl-Send-for-RwLock%3CT%3E
https://doc.rust-lang.org/std/sync/struct.RwLock.html#impl-Sync-for-RwLock%3CT%3E

For the second one, it looks like `impl<T: ?Sized + Send + Sync> Sync for RwLock<T>` is the correct bound, maybe?

2024-11-20 19:19 UTC, Gavin-Niederman commented on packages/vexide-core/src/sync/rwlock.rs
> +unsafe impl<T: ?Sized + Sync> Sync for RwLock<T> {}
Yeah that's correct. I wasn't thinking about how RwLock works.

2024-11-22 02:44 UTC, Gavin-Niederman requested changes

2024-11-22 02:44 UTC, Gavin-Niederman commented on packages/vexide-core/src/sync/rwlock.rs
>  impl<T> RwLock<T> {
This impl needs to also have a relaxed Sized bound.

2024-11-22 02:45 UTC, Gavin-Niederman commented on packages/vexide-core/src/sync/rwlock.rs
>  impl<T> RwLock<T> {
You might need to put the new function in its own impl without a relaxed Sized bound

2024-11-22 11:30 UTC, zabackary commented on packages/vexide-core/src/sync/rwlock.rs
>  impl<T> RwLock<T> {
Alternatively, the `new` function could be in this impl with a more restrictive `where T: Sized` clause

2024-11-23 21:17 UTC, Tropix126 approved these changes
LGTM

2024-11-24 00:27 UTC, Gavin-Niederman approved these changes
LGTM

2024-11-24 00:27 UTC, merged