feat(devices): add `with_initial_level` to `AdiDigitalOut`
vexide/vexide pull request #246
Opened 2024-11-22 12:12 UTC by zabackary

## Describe the changes this PR makes. Why should it be merged?

This PR adds a way to specify the initial level of a digital ADI port while creating the port. This simplifies the common use case of starting a competition with a pneumatic piston at a certain state.

## Additional Context

- semver: minor
- These changes update the crate's interface (e.g. functions/modules added or changed).

2024-11-22 18:34 UTC, Gavin-Niederman requested changes

2024-11-22 18:34 UTC, Gavin-Niederman commented on packages/vexide-devices/src/adi/digital.rs
> +    pub fn with_initial_level(port: AdiPort, initial_level: LogicLevel) -> Result<Self, PortError> {
In general we are against fallible constructors whenever possible because it can eat the SmartPort and is in general difficult to recover from, so it would be better if this is infallible.

2024-11-23 02:05 UTC, zabackary commented on packages/vexide-devices/src/adi/digital.rs
> +    pub fn with_initial_level(port: AdiPort, initial_level: LogicLevel) -> Result<Self, PortError> {
Should this not exist, then, or silently drop the error? It seems like something that would be useful.

2024-11-23 21:18 UTC, Tropix126 commented on packages/vexide-devices/src/adi/digital.rs
> +    pub fn with_initial_level(port: AdiPort, initial_level: LogicLevel) -> Result<Self, PortError> {
The error is not silently dropped; VEXos will save the value and set the port as soon as the expander is plugged back in.

2024-11-24 15:07 UTC, Tropix126 approved these changes
LGTM

2024-11-24 19:29 UTC, Gavin-Niederman approved these changes
LGTM

2024-11-24 19:30 UTC, merged