feat: add a way to set `Text` background color
vexide/vexide pull request #247
Opened 2024-11-22 14:34 UTC by zabackary

## Describe the changes this PR makes. Why should it be merged?

This PR adds the `Text::write` API for writing text to a `Display` with a background color.

This PR contains breaking changes. It changes the default background color of text written with the `Fill` trait from the last used background color (which is unpredictable and probably not the best default) to transparent.

## Additional Context

- I have tested these changes on a VEX V5 Brain.
- semver: major (see earlier). If you don't count that as a breaking change, then it's a minor change.
- These changes update the crate's interface (e.g. functions/modules added or changed).
- Fixes #69

2024-11-22 16:19 UTC, Gavin-Niederman submitted a review, later dismissed
I would consider moving the background color into the Text itself. This would remove the need for the special `write` syntax. Speaking of `write`, I'm not sure I like that it's called write because it doesn't work like the Write trait where the type implementing Write is being written to. Here the Text is writing to the display.

2024-11-23 01:26 UTC, zabackary commented
> I would consider moving the background color into the Text itself. This would remove the need for the special `write` syntax. Speaking of `write`, I'm not sure I like that it's called write because it doesn't work like the Write trait where the type implementing Write is being written to. Here the Text is writing to the display.

I'm going to implement it as discussed [here](https://github.com/vexide/vexide/issues/69#issuecomment-2495151661), if that's okay.

2024-11-26 23:29 UTC, doinkythederp requested changes

2024-11-26 23:29 UTC, doinkythederp commented on CHANGELOG.md
> +- Added `Fill` implementation for `Text`, since it's a bit of a special case. (#247)
This is outdated

2024-11-26 23:29 UTC, doinkythederp commented on packages/vexide-devices/src/display.rs
This workaround is no longer necessary with the latest changes from main, you can just pass `1` to `vexDisplayPrintf`

2024-11-26 23:29 UTC, doinkythederp commented on packages/vexide-devices/src/display.rs
> +    /// `Display::fill_text` to specify a background color.
This is outdated because Text doesn't implement Fill

2024-11-27 21:04 UTC, doinkythederp approved these changes

2024-11-29 04:23 UTC, Tropix126 approved these changes
LGTM

2024-11-29 04:23 UTC, merged