docs: Add examples for all the adi devices
vexide/vexide pull request #256
Opened 2024-12-10 13:18 UTC by zabackary

## Describe the changes this PR makes. Why should it be merged?

I had some time and did the not-fun work of adding examples. Hopefully they compile; it doesn't seem like there's a way to `cargo check` doctests yet.

## Additional Context

- These are *only* non-code changes (e.g. documentation, README.md).

2024-12-10 23:42 UTC, Gavin-Niederman approved these changes
LGTM otherwise. Ty :3

2024-12-10 23:43 UTC, Gavin-Niederman requested changes
Chose wrong type

2024-12-10 23:56 UTC, zabackary commented
> Chose wrong type

Wait, for what?

2024-12-11 03:28 UTC, Gavin-Niederman commented
> > Chose wrong type
> 
> Wait, for what?

I clicked the wrong review type and accidentally approved.

2024-12-13 16:16 UTC, Gavin-Niederman commented on packages/vexide-devices/src/adi/light_sensor.rs
> +    /// 0-5V measured by the V5 Brain's ADC.
Yes I think what you have is correct.

2024-12-17 21:01 UTC, Gavin-Niederman approved these changes
LGTM TYSM :3

2024-12-17 21:01 UTC, merged