refactor: turn errors caused by user end bugs into panics
vexide/vexide pull request #266
Opened 2024-12-22 22:21 UTC by Gavin-Niederman

## Describe the changes this PR makes. Why should it be merged?
This PR refactors most of the error variants in device errors caused by user end bugs into panics.
> Functions often have contracts: their behavior is only guaranteed if the inputs meet particular requirements. Panicking when the contract is violated makes sense because a contract violation always indicates a caller-side bug, and it’s not a kind of error you want the calling code to have to explicitly handle.
## Additional Context
- These are breaking changes (semver: major).

2024-12-23 02:02 UTC, zabackary reviewed
I know this is a draft, but here's some comments...

2024-12-23 02:02 UTC, zabackary commented on packages/vexide-devices/src/controller.rs
> -    /// - A [`ControllerError::Nul`] error if a NUL (0x00) character was
I'm of the opinion that this one shouldn't be the caller's responsibility to verify since a lot of times those messages aren't hard-coded, but it's up to your judgement. 

The other ones look good!

2024-12-24 21:13 UTC, Gavin-Niederman commented on packages/vexide-devices/src/controller.rs
> -    /// - A [`ControllerError::Nul`] error if a NUL (0x00) character was
Can you elaborate on what you mean? If the caller tries to put a message at invalid coordinates, it wouldn't even appear on screen if it wasn't checked.

2024-12-25 01:01 UTC, zabackary commented on packages/vexide-devices/src/controller.rs
> -    /// - A [`ControllerError::Nul`] error if a NUL (0x00) character was
Sorry, I guess I didn't leave the comment at a clear place, but I meant the last one (`ControllerError::Nul`).
Actually, after thinking about it more, it's probably fine. 

By the way, Merry Christmas!

2025-01-23 18:39 UTC, Tropix126 requested changes
changelog :3

2025-01-24 06:50 UTC, Tropix126 approved these changes
LGTM

2025-01-24 06:50 UTC, merged