test: patch uploading MVP
vexide/vexide pull request #269
Opened 2024-12-28 05:56 UTC by Tropix126

## Describe the changes this PR makes. Why should it be merged?

## Additional Context

2025-01-21 08:20 UTC, zabackary commented
I just got a panic using this related to allocation, but I have no idea what caused it. Also, the symbolizer extension doesn't work.

2025-01-21 15:36 UTC, Tropix126 commented
> I just got a panic using this related to allocation, but I have no idea what caused it. Also, the symbolizer extension doesn't work.

Panic is concerning, but likely a product of some other UB rather than an allocator issue. Symbolizer I wouldn't expect to work if the stack is possibly corrupted.

2025-01-22 22:41 UTC, ion098 requested changes

2025-01-22 22:41 UTC, ion098 commented on packages/vexide-startup/link/v5.ld
> +    /* -- End of loadable sections - anything beyond this point shouldnt go in the BIN. -- */
```suggestion
    /* -- End of loadable sections - anything beyond this point shouldn't go in the BIN. -- */
```

2025-01-22 22:41 UTC, ion098 commented on packages/vexide-startup/src/patcher/overwriter.S
> +    mcr p15, 0, r0, c7, c1, 0  @ ICIALLUIS
Maybe add a brief description of what `ICIALLIUS` stands for? (Similar to the one for `DCCMVAU` above)

2025-01-22 22:41 UTC, ion098 commented on packages/vexide-startup/src/lib.rs
> +    ldr r2, =0x07A0000C @ memcpy size -> r2
```suggestion
    ldr r2, =0x07A0000C @ the length of the binary is stored at 0x07A0000C
```

2025-01-22 22:41 UTC, ion098 commented on packages/vexide-startup/src/lib.rs
> +    ldr r2, [r2]
```suggestion
    ldr r2, [r2] @ memcpy size -> r2
```

2025-01-22 22:41 UTC, ion098 commented on packages/vexide-startup/src/patcher/overwriter_aeabi_memcpy.S
Does the LICENSE file need to be updated to exempt this file?

2025-01-23 07:32 UTC, Tropix126 commented on packages/vexide-startup/src/patcher/overwriter.S
> +    mcr p15, 0, r0, c7, c1, 0  @ ICIALLUIS
I included the comment for general posterity to save people from looking up the CP15 mneumonic on ARM's docs themselves. The explanation of what's actually being done is explained on line 26:
> Invalidate entire L1 instruction cache

2025-01-23 07:46 UTC, Tropix126 commented on packages/vexide-startup/src/patcher/overwriter_aeabi_memcpy.S
The BSD-3 clause is compatible with the MIT license and doesn't require exemption, but I've added ARM's license under a "Third-Party Licenses" section of our LICENSES file.

2025-01-25 00:48 UTC, Gavin-Niederman requested changes

2025-01-25 00:48 UTC, Gavin-Niederman commented on packages/vexide-startup/src/patcher/mod.rs
> +            // TODO(tropix126): We could reclaim the patch as heap space maybe? Not a high priority.
If you are doing this after the patch has been successfully applied surely you can here too right?

2025-01-25 01:42 UTC, Gavin-Niederman approved these changes
LGTM

2025-01-25 01:44 UTC, merged