refactor: replace `ColdHeader` with `CodeSignature`
vexide/vexide pull request #76
Opened 2024-05-28 05:07 UTC by Tropix126

## Describe the changes this PR makes. Why should it be merged?
- Replaces the previous `ColdHeader` type with a higer-level `CodeSignature` type.
- Code signature is now part of vexide_core's program module and newtypes `vex_sdk::vcodesig`.
- Update to `vex-sdk` 0.17.0.

## Additional Context
Requires testing to ensure boot flags work as intended.

2024-05-29 01:07 UTC, doinkythederp commented on packages/vexide-startup/src/lib.rs
> +pub struct CodeSignature(vex_sdk::vcodesig, [u32; 4]);
What's the purpose of the extra 4 bytes? Are they just padding to get to 0x20?

2024-06-15 21:58 UTC, doinkythederp submitted a review, later dismissed

2024-06-15 21:58 UTC, doinkythederp commented on packages/vexide-startup/src/lib.rs
> +        /// Default graphics colors (foreground/background) will be inverted.
From my testing these display inversion flags don't affect foreground color (it always starts as `#c0c0ff`).

2024-06-15 21:58 UTC, doinkythederp commented on packages/vexide-startup/src/lib.rs
> +        const THEMED_DEFAULT_GRAPHICS = 1 << 2;
It might be good to specify than when both inversion options are specified, the themed one "wins".

2024-06-17 14:57 UTC, Tropix126 commented
Latest changes need testing

2024-07-01 21:44 UTC, Gavin-Niederman requested changes
Just this.

2024-07-01 21:44 UTC, Gavin-Niederman commented on packages/vexide-startup/link/v5.ld
> +__heap_end = __user_ram_end - __stack_length - 0x100;
I think its worth keeping the documentation for this subtraction.

2024-07-01 21:59 UTC, Gavin-Niederman approved these changes
LGTM

2024-07-01 22:01 UTC, merged