feat: Add support for floating-point math
vexide/vexide pull request #77
Opened 2024-05-30 05:28 UTC by Tropix126

## Describe the changes this PR makes. Why should it be merged?
Floating-point math in Rust is implemented as part of `std` and not `core`, due to reliance on optimized LLVM intriniscs that aren't portable or available for our platform. It additionally links to cmath in some cases, where a platform libc is expected. This PR reimplements all missing fp math functionality through a `Float` extension trait (implemented for `f32` and `f64` and included in the prelude). This is done by linking to a static `libm` that's part of the ARM gcc toolchain and stubbing the necessary symbols expected of libc (just `__errno`).

This should be anywhere from 4-10 times faster than existing solutions, due to this version of libm utilizing the hard float ABI as well as vfp3 instructions, as opposed to existing no_std solutions like [rust-lang/libm](https://github.com/rust-lang/libm/) being implemented entirely with soft floats.

## Additional Context
![image](https://github.com/vexide/vexide/assets/42101043/d428501e-48a6-4caa-867e-c29ffeca1e82)

2024-05-31 01:14 UTC, doinkythederp requested changes

2024-05-31 01:14 UTC, doinkythederp commented on packages/vexide-startup/build.rs
> +    println!("cargo:rustc-link-lib=static=m");
This does not compile to WebAssembly targets.

2024-05-31 01:18 UTC, doinkythederp commented on packages/vexide-startup/build.rs
> +    println!("cargo:rustc-link-lib=static=m");
Compile time link error:

```
error: linking with `rust-lld` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/Users/lewis/.rustup/toolchains/nightly-2024-02-07-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/lewis/.rustup/toolchains/nightly-2024-02-07-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin/self-contained:/opt/homebrew/opt/ruby/bin:/Users/lewis/.wasmtime/bin:/Users/lewis/.aftman/bin:/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/lewis/.foreman/bin:/Users/lewis/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/lewis/.aftman/bin:/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/ruby/bin:/Users/lewis/.wasmtime/bin:/Users/lewis/.aftman/bin:/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/lewis/.foreman/bin:/Users/lewis/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/lewis/.aftman/bin:/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/Caskroom/miniconda/base/condabin:/opt/homebrew/opt/ruby/bin:/Users/lewis/.wasmtime/bin:/Users/lewis/.aftman/bin:/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/lewis/.foreman/bin:/Users/lewis/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/lewis/.aftman/bin:/Users/lewis/.cargo/bin:/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/lewis/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/Users/lewis/.orbstack/bin:/opt/homebrew/opt/binutils/bin:/Users/lewis/.local/bin:/Users/lewis/.orbstack/bin:/opt/homebrew/opt/binutils/bin:/Users/lewis/.local/bin:/Users/lewis/.orbstack/bin:/opt/homebrew/opt/binutils/bin:/Users/lewis/.local/bin" VSLANG="1033" "rust-lld" "-flavor" "wasm" "--rsp-quoting=posix" "--export" "_entry" "--export" "main" "--export" "__errno" "--export" "_critical_section_1_0_acquire" "--export" "_critical_section_1_0_release" "--export" "wasm_free" "--export" "wasm_memalign" "--export" "vexBackgroundProcessing" "--export" "vexBatteryCapacityGet" "--export" "vexBatteryCurrentGet" "--export" "vexBatteryTemperatureGet" "--export" "vexBatteryVoltageGet" "--export" "vexCompetitionControl" "--export" "vexCompetitionStatus" "--export" "vexControllerConnectionStatusGet" "--export" "vexControllerGet" "--export" "vexControllerTextSet" "--export" "vexDeviceAbsEncAngleGet" "--export" "vexDeviceAbsEncDataRateSet" "--export" "vexDeviceAbsEncPositionGet" "--export" "vexDeviceAbsEncPositionSet" "--export" "vexDeviceAbsEncReset" "--export" "vexDeviceAbsEncReverseFlagGet" "--export" "vexDeviceAbsEncReverseFlagSet" "--export" "vexDeviceAbsEncStatusGet" "--export" "vexDeviceAbsEncTemperatureGet" "--export" "vexDeviceAbsEncVelocityGet" "--export" "vexDeviceAdiAddrLedSet" "--export" "vexDeviceAdiPortConfigGet" "--export" "vexDeviceAdiPortConfigSet" "--export" "vexDeviceAdiValueGet" "--export" "vexDeviceAdiValueSet" "--export" "vexDeviceAiVisionClassNameGet" "--export" "vexDeviceAiVisionCodeGet" "--export" "vexDeviceAiVisionCodeSet" "--export" "vexDeviceAiVisionColorGet" "--export" "vexDeviceAiVisionColorSet" "--export" "vexDeviceAiVisionModeGet" "--export" "vexDeviceAiVisionModeSet" "--export" "vexDeviceAiVisionObjectCountGet" "--export" "vexDeviceAiVisionObjectGet" "--export" "vexDeviceAiVisionSensorSet" "--export" "vexDeviceAiVisionStatusGet" "--export" "vexDeviceAiVisionTemperatureGet" "--export" "vexDeviceArmBatteryGet" "--export" "vexDeviceArmBootload" "--export" "vexDeviceArmClearZeroValues" "--export" "vexDeviceArmDebugGet" "--export" "vexDeviceArmDropCommand" "--export" "vexDeviceArmEnableProfiler" "--export" "vexDeviceArmForceZeroCommand" "--export" "vexDeviceArmFullStop" "--export" "vexDeviceArmJ6PositionGet" "--export" "vexDeviceArmJ6PositionSet" "--export" "vexDeviceArmJointErrorsGet" "--export" "vexDeviceArmJointInfoGet" "--export" "vexDeviceArmMoveJointsCommand" "--export" "vexDeviceArmMoveTipCommandJoint" "--export" "vexDeviceArmMoveTipCommandJointAdv" "--export" "vexDeviceArmMoveTipCommandLinear" "--export" "vexDeviceArmMoveTipCommandLinearAdv" "--export" "vexDeviceArmMoveVoltsCommand" "--export" "vexDeviceArmPickUpCommand" "--export" "vexDeviceArmPoseSet" "--export" "vexDeviceArmProfilerVelocitySet" "--export" "vexDeviceArmReboot" "--export" "vexDeviceArmSaveZeroValues" "--export" "vexDeviceArmServoFlagsGet" "--export" "vexDeviceArmSetJointPositions" "--export" "vexDeviceArmSpinJoints" "--export" "vexDeviceArmStatusGet" "--export" "vexDeviceArmStopJointsCommand" "--export" "vexDeviceArmTipOffsetSet" "--export" "vexDeviceArmTipPositionGet" "--export" "vexDeviceArmTipPositionGetAdv" "--export" "vexDeviceBumperGet" "--export" "vexDeviceButtonStateGet" "--export" "vexDeviceDistanceConfidenceGet" "--export" "vexDeviceDistanceDistanceGet" "--export" "vexDeviceDistanceObjectSizeGet" "--export" "vexDeviceDistanceObjectVelocityGet" "--export" "vexDeviceDistanceStatusGet" "--export" "vexDeviceFlagsGetByIndex" "--export" "vexDeviceGenericRadioConnection" "--export" "vexDeviceGenericRadioLinkStatus" "--export" "vexDeviceGenericRadioReceive" "--export" "vexDeviceGenericRadioReceiveAvail" "--export" "vexDeviceGenericRadioTransmit" "--export" "vexDeviceGenericRadioWriteFree" "--export" "vexDeviceGenericSerialBaudrate" "--export" "vexDeviceGenericSerialEnable" "--export" "vexDeviceGenericSerialFlush" "--export" "vexDeviceGenericSerialPeekChar" "--export" "vexDeviceGenericSerialReadChar" "--export" "vexDeviceGenericSerialReceive" "--export" "vexDeviceGenericSerialReceiveAvail" "--export" "vexDeviceGenericSerialTransmit" "--export" "vexDeviceGenericSerialWriteChar" "--export" "vexDeviceGenericSerialWriteFree" "--export" "vexDeviceGenericValueGet" "--export" "vexDeviceGetByIndex" "--export" "vexDeviceGetStatus" "--export" "vexDeviceGetTimestamp" "--export" "vexDeviceGpsAttitudeGet" "--export" "vexDeviceGpsDataRateSet" "--export" "vexDeviceGpsDegreesGet" "--export" "vexDeviceGpsErrorGet" "--export" "vexDeviceGpsHeadingGet" "--export" "vexDeviceGpsInitialPositionSet" "--export" "vexDeviceGpsModeGet" "--export" "vexDeviceGpsModeSet" "--export" "vexDeviceGpsOriginGet" "--export" "vexDeviceGpsOriginSet" "--export" "vexDeviceGpsQuaternionGet" "--export" "vexDeviceGpsRawAccelGet" "--export" "vexDeviceGpsRawGyroGet" "--export" "vexDeviceGpsReset" "--export" "vexDeviceGpsRotationGet" "--export" "vexDeviceGpsRotationSet" "--export" "vexDeviceGpsStatusGet" "--export" "vexDeviceGpsTemperatureGet" "--export" "vexDeviceGyroDegreesGet" "--export" "vexDeviceGyroHeadingGet" "--export" "vexDeviceGyroReset" "--export" "vexDeviceImuAttitudeGet" "--export" "vexDeviceImuDataRateSet" "--export" "vexDeviceImuDegreesGet" "--export" "vexDeviceImuHeadingGet" "--export" "vexDeviceImuModeGet" "--export" "vexDeviceImuModeSet" "--export" "vexDeviceImuQuaternionGet" "--export" "vexDeviceImuRawAccelGet" "--export" "vexDeviceImuRawGyroGet" "--export" "vexDeviceImuReset" "--export" "vexDeviceImuStatusGet" "--export" "vexDeviceImuTemperatureGet" "--export" "vexDeviceLedGet" "--export" "vexDeviceLedRgbGet" "--export" "vexDeviceLedRgbSet" "--export" "vexDeviceLedSet" "--export" "vexDeviceLightTowerBlinkSet" "--export" "vexDeviceLightTowerColorSet" "--export" "vexDeviceLightTowerDebugGet" "--export" "vexDeviceLightTowerRgbGet" "--export" "vexDeviceLightTowerRgbSet" "--export" "vexDeviceLightTowerStatusGet" "--export" "vexDeviceLightTowerXywGet" "--export" "vexDeviceMagnetCurrentGet" "--export" "vexDeviceMagnetDrop" "--export" "vexDeviceMagnetPickup" "--export" "vexDeviceMagnetPowerGet" "--export" "vexDeviceMagnetPowerSet" "--export" "vexDeviceMagnetStatusGet" "--export" "vexDeviceMagnetTemperatureGet" "--export" "vexDeviceMotorAbsoluteTargetSet" "--export" "vexDeviceMotorActualVelocityGet" "--export" "vexDeviceMotorBrakeModeGet" "--export" "vexDeviceMotorBrakeModeSet" "--export" "vexDeviceMotorCurrentGet" "--export" "vexDeviceMotorCurrentLimitFlagGet" "--export" "vexDeviceMotorCurrentLimitGet" "--export" "vexDeviceMotorCurrentLimitSet" "--export" "vexDeviceMotorDirectionGet" "--export" "vexDeviceMotorEfficiencyGet" "--export" "v [...]

2024-05-31 01:39 UTC, Gavin-Niederman commented
Can you make a feature for rust libm vs c libm?

2024-06-01 00:34 UTC, doinkythederp requested changes

2024-06-01 00:34 UTC, doinkythederp commented on packages/vexide-core/src/float/mod.rs
> +    /// Windows. Note that this might change in the future.
I don't think this comment is relevant since we don't support either Unix or Windows as a target.

2024-06-01 00:34 UTC, doinkythederp commented on packages/vexide-core/src/float/mod.rs
> +    fn abs_sub(self, other: Self) -> Self;
Do we really want to make new functions that are already deprecated? It might be better to just not add them in the first place.

2024-06-01 04:02 UTC, Tropix126 commented on packages/vexide-core/src/float/mod.rs
> +    /// Windows. Note that this might change in the future.
I'll remove the specific comment regarding windows/unix, although the precision part still applies across ARM32 and WASM

2024-06-01 04:03 UTC, Tropix126 commented on packages/vexide-core/src/float/mod.rs
> +    fn abs_sub(self, other: Self) -> Self;
I do think its a good idea to have parity with the standard library here, even though the function may not be of use to many people.

2024-06-01 19:30 UTC, doinkythederp commented on packages/vexide-core/src/float/mod.rs
> +    fn abs_sub(self, other: Self) -> Self;
OK

2024-06-01 19:31 UTC, doinkythederp approved these changes

2024-06-01 22:55 UTC, merged