Display string using vargs to escape
vexide/vexide pull request #84
Opened 2024-06-04 23:29 UTC by alexDickhans

Fixes unsafe behavior in Text widget related to printf-esque formatting of strings passed into vexDisplayStringAt().

I can't test these changes today, but I'm getting some tomorrow. Should be easy to test.

2024-06-07 05:38 UTC, alexDickhans commented
Tested today

Code:
```rust
#![no_main]
#![no_std]

use core::time::Duration;

use vexide::prelude::*;
use vexide_devices::screen::*;

#[vexide::main]
async fn main(peripherals: Peripherals) {
    println!("Hello, world!");
    let mut screen = peripherals.screen;

    let mut text = Text::new("Test Text%d", TextSize::Medium, (0, 0));
    text.fill(&mut screen, Rgb::new(0, 255, 255));

    loop {
        sleep(Duration::from_millis(1)).await;
    }
}
```
Results:

![2024-06-06-233749_480x272_pros_capture](https://github.com/vexide/vexide/assets/55064247/36911cc0-e5a9-4bef-9a27-fd76a1077b83)

2024-06-07 06:05 UTC, doinkythederp requested changes
I think you may have missed a few places where variable argument functions are used (e.g. [here](https://github.com/alexDickhans/vexide/blob/e2cac0b338724e70ba0da55aaf61221af3a49caf/packages/vexide-devices/src/screen.rs#L50)). Make sure you've covered all the calls to these functions:

- vexDisplayPrintf
- vexDisplayString
- vexDisplayStringAt
- vexDisplayBigString
- vexDisplayBigStringAt
- vexDisplaySmallStringAt
- vexDisplayCenteredString
- vexDisplayBigCenteredString
- vex_printf
- vex_sprintf
- vex_snprintf

2024-06-08 05:19 UTC, alexDickhans commented
Fixed all those functions too, new test code:
```rust
#![no_main]
#![no_std]

use core::{fmt::Write, time::Duration};

use vexide::prelude::*;
use vexide_devices::screen::*;

#[vexide::main]
async fn main(peripherals: Peripherals) {
    println!("Hello, world!");
    let mut screen = peripherals.screen;

    screen.write_str("Hello world!%d").unwrap();

    loop {
        sleep(Duration::from_millis(1)).await;
    }
}
```

2024-06-10 04:27 UTC, doinkythederp approved these changes

2024-06-10 04:28 UTC, merged