feat: Add text alignment to Text widget
vexide/vexide pull request #85
Opened 2024-06-04 23:55 UTC by alexDickhans

This pr adds a text alignment feature to Text widgets using the .width and .height methods

Can't test this today, but I can tomorrow

2024-06-04 23:56 UTC, alexDickhans commented
Fixes #72

2024-06-07 05:36 UTC, alexDickhans commented
Tested today! It works!

Code:
```rust
#![no_main]
#![no_std]

use core::time::Duration;

use vexide::prelude::*;
use vexide_devices::screen::*;

#[vexide::main]
async fn main(peripherals: Peripherals) {
    println!("Hello, world!");
    let mut screen = peripherals.screen;

    let mut text = Text::new("Test Text", TextSize::Medium, (0, 0));
    text.align(HAlign::Center, VAlign::Top);
    text.fill(&mut screen, Rgb::new(0, 255, 255));

    loop {
        sleep(Duration::from_millis(1)).await;
    }
}
```

2024-06-07 06:20 UTC, doinkythederp requested changes

2024-06-07 06:20 UTC, doinkythederp commented on packages/vexide-devices/src/screen.rs
> +#[derive(Debug, Clone, Eq, PartialEq)]
This and VAlign should probably also derive Copy and Default.

2024-06-07 06:20 UTC, doinkythederp commented on packages/vexide-devices/src/screen.rs
> +            vertical_align: VAlign::Top,
If you end up implementing Default, this could be changed to `HAlign::default()`.

2024-06-07 06:20 UTC, doinkythederp commented on packages/vexide-devices/src/screen.rs
> +    }
I think you should update `Text::new` to delegate to this new function under the hood to help reduce code duplication.

2024-06-07 06:20 UTC, doinkythederp commented on packages/vexide-devices/src/screen.rs
> +        let height = self.height();
Text metrics should not be calculated in situations where they are not used.

2024-06-07 06:20 UTC, doinkythederp commented on packages/vexide-devices/src/screen.rs
> +    /// Input coordinate is at the left of the text box; default for text displaying
I think it would make more sense to move "default for text displaying" to the `Text::new` docs since that is currently the only situation where the library actually assumes a default.

2024-06-07 14:59 UTC, alexDickhans commented on packages/vexide-devices/src/screen.rs
> +    /// Input coordinate is at the left of the text box; default for text displaying
Its already in the docs there a little, I'll add to it a little

2024-06-08 04:54 UTC, alexDickhans commented on packages/vexide-devices/src/screen.rs
> +    /// Input coordinate is at the left of the text box; default for text displaying
Done

2024-06-08 04:54 UTC, alexDickhans commented on packages/vexide-devices/src/screen.rs
> +        let height = self.height();
Done

2024-06-08 04:55 UTC, alexDickhans commented on packages/vexide-devices/src/screen.rs
> +    }
Done

2024-06-08 04:55 UTC, alexDickhans commented on packages/vexide-devices/src/screen.rs
> +            vertical_align: VAlign::Top,
Done

2024-06-08 04:55 UTC, alexDickhans commented on packages/vexide-devices/src/screen.rs
> +#[derive(Debug, Clone, Eq, PartialEq)]
Done

2024-06-08 05:03 UTC, doinkythederp approved these changes

2024-06-08 20:39 UTC, merged