feat: add `cargo run` runner
vexide/vexide pull request #99
Opened 2024-06-14 04:37 UTC by doinkythederp

## Describe the changes this PR makes. Why should it be merged?

This PR adds a cargo runner config, allowing developers to succinctly upload, run, and view the serial output of examples by simply typing `cargo run --example <EXAMPLE>`.

It uses Google's cross-platform `zx` command as an alternative to a shell script in order to support all 3 host platforms in one file.

## Additional Context
- I have tested these changes on a VEX V5 brain.
- I have tested these changes on Mac and Linux (nix flake on Debian) but not yet Windows.

2024-06-14 06:38 UTC, doinkythederp commented
I might refactor this to live in cargo-pros so I don't need to add a dependency.

2024-06-14 07:27 UTC, doinkythederp commented
Requires a recent git build of cargo-pros to work properly.

2024-06-15 00:33 UTC, doinkythederp commented
Flake lock needs to be updated before a merge

2024-06-17 02:43 UTC, Gavin-Niederman requested changes
I dislike the fact that you can only upload to slot one. There might be some way around this, but it feels wrong to me to do this.

2024-06-17 05:13 UTC, Gavin-Niederman requested changes

2024-06-17 05:13 UTC, Gavin-Niederman commented on README.md
> +After setting up your development environment, connect to a VEX V5 via USB and run `cargo run --example basic` to execute the basic example on the V5 brain. Try the other examples like `screen` or `c
You should clarify that cargo run doesn't work in the template and that you have to use cargo pros.

2024-07-12 00:09 UTC, Tropix126 commented
Given the recent release of cargo-v5, i'm thinking we might want to write a new runner that's also present in the template for this. (just runs `cargo v5 upload --after=run && cargo v5 terminal`). Slot number limitations are no longer a concern since those are either prompted or configured in Cargo.toml now.

I'm not sure if the runner functionality should be all decentralized as it might be worthwhile to push updates to it though, so maybe we should slap it into a crate or integrate it into `cargo v5`.

2024-07-12 01:22 UTC, doinkythederp commented
> Given the recent release of cargo-v5, i'm thinking we might want to write a new runner that's also present in the template for this. (just runs `cargo v5 upload --after=run && cargo v5 terminal`). Slot number limitations are no longer a concern since those are either prompted or configured in Cargo.toml now.
> 
> I'm not sure if the runner functionality should be all decentralized as it might be worthwhile to push updates to it though, so maybe we should slap it into a crate or integrate it into `cargo v5`.

The existence of `cargo pros run` for compiling and uploading and running and terminal at the same time was actually necessary because otherwise there is a risk of serial data being lost between the two shell commands as the program runs. Also the naive approach of chaining the two commands together presumably wouldn't work on windows because of the &&. Thus I think it should stay integrated into the cli.

2024-07-12 01:24 UTC, doinkythederp commented
I get back from traveling tomorrow so I might be able to work on implementing `cargo v5 run` so this PR can be updated.

2024-07-12 02:51 UTC, Tropix126 commented
Sounds good. The terminal issue can now be circumvented as we have the ability to start/stop programs at any time.

2024-09-11 05:40 UTC, doinkythederp commented
Ready for review

2024-09-11 05:42 UTC, doinkythederp commented
This would be pretty useful to add to the template too to increase usability for people who aren't familiar with the terminal ![run button](https://private-user-images.githubusercontent.com/75394401/339676154-e71dbd97-1c3c-4a54-bee7-25f5049b6f59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzM0MzUsIm5iZiI6MTcyNjAzMzEzNSwicGF0aCI6Ii83NTM5NDQwMS8zMzk2NzYxNTQtZTcxZGJkOTctMWMzYy00YTU0LWJlZTctMjVmNTA0OWI2ZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA1Mzg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyM2M1YmY5NmExMzAxZThhOWE1MzVhY2UwOWFmZjZkMWRjMjRiNjBmNTMyYmUzMTBmYzMxZWY4MWU4MTVjYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yj1ioaETWPR5q55INNPurGeDS3sk12zlZ645c5WC7CM)

2024-09-19 03:23 UTC, Gavin-Niederman approved these changes
LLLGMGGGMMMTMMMMMMM 
![{2B6D9742-0EAA-4FCD-98C7-84DDC3E7861D}](https://github.com/user-attachments/assets/fcb2a608-7a1c-40ed-a7cf-ac1f4869c974)

2024-09-19 03:29 UTC, Gavin-Niederman approved these changes
LGMTLMTLMMMLLMGMMMMMMMMMMMMMMM
![{09924143-944A-441D-9379-C293AD6C0DB4}](https://github.com/user-attachments/assets/0256440b-1447-4f51-9fbf-b82346a57c04)
M :4 :3 :3

2024-09-19 03:30 UTC, merged